import type { SymbolLayerSpecification } from "maplibre-gl";

export const layersPoi: SymbolLayerSpecification[] = [
	{
		id: "historic-petroglyph",
		type: "symbol",
		source: "world",
		"source-layer": "poi",
		filter: ["==", ["get", "archaeological_site"], "petroglyph"],
		minzoom: 8,
		layout: {
			"icon-image": "extras:shape-diamond",
			"icon-size": 0.4,
			"text-field": [
				"coalesce",
				["get", "name:de"],
				["get", "name:en"],
				["get", "name"],
			],
			"text-font": ["noto_sans_regular"],
			"text-size": 11,
			"text-anchor": "top",
			"text-offset": [0, 0.6],
			"text-max-width": 8,
		},
		paint: {
			"icon-color": "#8a6a4a",
			"text-color": "#6b5843",
			"text-halo-color": "rgba(255, 255, 255, 0.85)",
			"text-halo-width": 1.5,
			"text-halo-blur": 1,
		},
	},
	{
		id: "historic-fortification",
		type: "symbol",
		source: "world",
		"source-layer": "poi",
		filter: ["==", ["get", "archaeological_site"], "fortification"],
		minzoom: 8,
		layout: {
			"icon-image": "extras:shape-hexagon_outline",
			"icon-size": 0.5,
			"text-field": [
				"coalesce",
				["get", "name:de"],
				["get", "name:en"],
				["get", "name"],
			],
			"text-font": ["noto_sans_regular"],
			"text-size": 11,
			"text-anchor": "top",
			"text-offset": [0, 0.6],
			"text-max-width": 8,
		},
		paint: {
			"icon-color": "#8a6a4a",
			"text-color": "#6b5843",
			"text-halo-color": "rgba(255, 255, 255, 0.85)",
			"text-halo-width": 1.5,
			"text-halo-blur": 1,
		},
	},
	{
		id: "land-rock",
		type: "symbol",
		source: "world",
		"source-layer": "poi",
		filter: [
			"in",
			[
				"coalesce",
				["get", "natural"],
				["get", "attraction"],
				["get", "tourism"],
			],
			["literal", ["rock", "nature", "viewpoint"]],
		],
		minzoom: 8,
		layout: {
			"icon-image": "extras:shape-triangle",
			"icon-size": 0.6,
			"text-field": [
				"coalesce",
				["get", "name:de"],
				["get", "name:en"],
				["get", "name"],
			],
			"text-font": ["noto_sans_regular"],
			"text-size": 11,
			"text-anchor": "top",
			"text-offset": [0, 0.6],
			"text-max-width": 8,
		},
		paint: {
			"icon-color": "#8a6a4a",
			"text-color": "#6b5843",
			"text-halo-color": "rgba(255, 255, 255, 0.85)",
			"text-halo-width": 1.5,
			"text-halo-blur": 1,
		},
	},
	{
		id: "poi-water",
		type: "symbol",
		source: "world",
		"source-layer": "poi",
		filter: [
			"in",
			["coalesce", ["get", "amenity"], ["get", "man_made"], ["get", "natural"]],
			["literal", ["drinking_water", "water_point", "water_well", "spring"]],
		],
		minzoom: 8,
		layout: {
			"icon-image": "extras:shape-drop",
			"icon-size": 0.6,
			"text-field": [
				"coalesce",
				["get", "name:de"],
				["get", "name:en"],
				["get", "name"],
			],
			"text-font": ["noto_sans_regular"],
			"text-size": 11,
			"text-anchor": "top",
			"text-offset": [0, 0.6],
			"text-max-width": 8,
		},
		paint: {
			"icon-color": "#2e7bb0",
			"text-color": "#2e5871",
			"text-halo-color": "rgba(255, 255, 255, 0.85)",
			"text-halo-width": 1.5,
			"text-halo-blur": 1,
		},
	},
	{
		id: "poi-fuel",
		type: "symbol",
		source: "world",
		"source-layer": "poi",
		filter: ["==", ["get", "amenity"], "fuel"],
		minzoom: 8,
		layout: {
			"icon-image": "extras:shape-circle",
			"icon-size": 0.6,
			"text-field": [
				"coalesce",
				["get", "name:de"],
				["get", "name:en"],
				["get", "name"],
			],
			"text-font": ["noto_sans_regular"],
			"text-size": 11,
			"text-anchor": "top",
			"text-offset": [0, 0.6],
			"text-max-width": 8,
		},
		paint: {
			"icon-color": "#c2691d",
			"text-color": "#8f4c14",
			"text-halo-color": "rgba(255, 255, 255, 0.85)",
			"text-halo-width": 1.5,
			"text-halo-blur": 1,
		},
	},
	{
		id: "poi-camp",
		type: "symbol",
		source: "world",
		"source-layer": "poi",
		filter: [
			"in",
			["get", "tourism"],
			["literal", ["camp_site", "wilderness_hut"]],
		],
		minzoom: 5,
		layout: {
			"icon-image": "extras:shape-pentagon",
			"icon-size": 0.6,
			"text-field": [
				"coalesce",
				["get", "name:de"],
				["get", "name:en"],
				["get", "name"],
			],
			"text-font": ["noto_sans_regular"],
			"text-size": 11,
			"text-anchor": "top",
			"text-offset": [0, 0.6],
			"text-max-width": 8,
		},
		paint: {
			"icon-color": "#4a7c4e",
			"text-color": "#375c39",
			"text-halo-color": "rgba(255, 255, 255, 0.85)",
			"text-halo-width": 1.5,
			"text-halo-blur": 1,
		},
	},
	{
		id: "historic-fort",
		type: "symbol",
		source: "world",
		"source-layer": "poi",
		filter: ["==", ["get", "historic"], "fort"],
		minzoom: 8,
		layout: {
			"icon-image": "extras:shape-rounded_square",
			"icon-size": 0.5,
			"text-field": [
				"coalesce",
				["get", "name:de"],
				["get", "name:en"],
				["get", "name"],
			],
			"text-font": ["noto_sans_regular"],
			"text-size": 11,
			"text-anchor": "top",
			"text-offset": [0, 0.6],
			"text-max-width": 8,
		},
		paint: {
			"icon-color": "#8a6a4a",
			"text-color": "#6b5843",
			"text-halo-color": "rgba(255, 255, 255, 0.85)",
			"text-halo-width": 1.5,
			"text-halo-blur": 1,
		},
	},
	{
		id: "historic-ruins",
		type: "symbol",
		source: "world",
		"source-layer": "poi",
		filter: ["==", ["get", "historic"], "ruins"],
		minzoom: 8,
		layout: {
			"icon-image": "extras:shape-diamond_outline",
			"icon-size": 0.4,
			"text-field": [
				"coalesce",
				["get", "name:de"],
				["get", "name:en"],
				["get", "name"],
			],
			"text-font": ["noto_sans_regular"],
			"text-size": 11,
			"text-anchor": "top",
			"text-offset": [0, 0.6],
			"text-max-width": 8,
		},
		paint: {
			"icon-color": "#8a6a4a",
			"text-color": "#6b5843",
			"text-halo-color": "rgba(255, 255, 255, 0.85)",
			"text-halo-width": 1.5,
			"text-halo-blur": 1,
		},
	},
	{
		id: "land-cave",
		type: "symbol",
		source: "world",
		"source-layer": "poi",
		filter: ["==", ["get", "natural"], "cave_entrance"],
		minzoom: 8,
		layout: {
			"icon-image": "extras:shape-hexagon",
			"icon-size": 0.5,
			"text-field": [
				"coalesce",
				["get", "name:de"],
				["get", "name:en"],
				["get", "name"],
			],
			"text-font": ["noto_sans_regular"],
			"text-size": 11,
			"text-anchor": "top",
			"text-offset": [0, 0.6],
			"text-max-width": 8,
		},
		paint: {
			"icon-color": "#5a5a5a",
			"text-color": "#3f3f3f",
			"text-halo-color": "rgba(255, 255, 255, 0.85)",
			"text-halo-width": 1.5,
			"text-halo-blur": 1,
		},
	},
	{
		id: "poi-border-control",
		type: "symbol",
		source: "world",
		"source-layer": "poi",
		filter: ["==", ["get", "barrier"], "border_control"],
		minzoom: 8,
		layout: {
			"icon-image": "extras:shape-octagon",
			"icon-size": 0.6,
			"text-field": [
				"coalesce",
				["get", "name:de"],
				["get", "name:en"],
				["get", "name"],
			],
			"text-font": ["noto_sans_regular"],
			"text-size": 11,
			"text-anchor": "top",
			"text-offset": [0, 0.6],
			"text-max-width": 8,
		},
		paint: {
			"icon-color": "#b23b3b",
			"text-color": "#8a2c2c",
			"text-halo-color": "rgba(255, 255, 255, 0.85)",
			"text-halo-width": 1.5,
			"text-halo-blur": 1,
		},
	},
];
